assets: /workspace/libero-assets
bddl_files: /workspace/LIBERO-sim/libero/libero/bddl_files
benchmark_root: /workspace/LIBERO-sim/libero/libero
datasets: /workspace/libero_spatial_image
init_states: /workspace/LIBERO-sim/libero/libero/init_files
