task_suite_name: libero_spatial
seed: 0
group_size: 1
use_fixed_reset_state_ids: true
use_ordered_reset_state_ids: true
specific_reset_id: 0
task_id_filter: [0]
ignore_terminations: false
auto_reset: false
is_eval: true
use_rel_reward: true
use_step_penalty: false
reward_coef: 1.0
reset_gripper_open: true
max_episode_steps: 240
video_cfg:
  save_video: true
  info_on_video: false
  video_base_dir: /home/caoyuhao/QVGM/outputs/phase_5
init_params:
  camera_heights: 256
  camera_widths: 256
